plugins:
  westlife_workflows:
    executor: central_deployment_agent
    source: https://github.com/vholer/cloudify-westlife-workflows/archive/master.zip
    package_name: cloudify-westlife-workflows
    package_version: '0.0.6'

workflows:
  scale_min_max:
    mapping: westlife_workflows.cloudify_westlife_workflows.scale_min_max.scale_min_max
    parameters:
      scalable_entity_name:
        description: >
          Which node/group to scale. Note that the parameter specified
          should denote the node/group name and NOT the node/group instance id.
      delta:
        description: >
            How many node/group instances should be added/removed.
            A positive number denotes increase of instances.
            A negative number denotes decrease of instances.
        default: 1
      scale_compute:
        description: >
            If a node name is passed as the `scalable_entity_name` parameter
            and that node is contained (transitively) within a compute node
            and this property is 'true', operate on the compute node instead
            of the specified node.
        default: false
      min_instances:
        description: The minimum number of allowed instances
        default: 1
      max_instances:
        description: The maximum number of allowed instances
        default: 100
